# Generated by Django 4.1.7 on 2023-12-09 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_remove_producto_precio_bs_alter_producto_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merma',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.producto'),
        ),
    ]
