# Generated by Django 4.1.7 on 2023-12-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='tipo_cambio',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
        ),
    ]
