# Generated by Django 4.1.7 on 2023-12-09 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='viaje',
        ),
    ]
