# Generated by Django 4.1.7 on 2023-12-09 16:56

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=200, null=True)),
                ('vendedor', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, max_length=25, null=True)),
                ('total_dolares', models.DecimalField(decimal_places=2, max_digits=10, max_length=25, null=True)),
                ('total_bolivianos', models.DecimalField(decimal_places=2, max_digits=10, max_length=25, null=True)),
                ('nombre_factura', models.CharField(blank=True, max_length=200, null=True, verbose_name='Vendedor')),
                ('nit', models.IntegerField(blank=True, null=True)),
                ('razon_cancelacion', models.CharField(blank=True, max_length=200, null=True)),
                ('entregado', models.BooleanField(default=False)),
                ('estado', django_fsm.FSMIntegerField(choices=[(0, 'creada'), (1, 'pagada'), (2, 'facturada'), (3, 'finalizada'), (4, 'cancelada'), (5, 'anulada')], default=0, protected=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('moneda', models.CharField(choices=[('Pesos', 'Pesos'), ('Dolares', 'Dolares'), ('Bolivianos', 'Bolivianos')], default=1, max_length=30)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=25)),
                ('precio', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.venta')),
            ],
        ),
    ]
